name: CI

on:
  push:
    branches:
    - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Run Forge Format
        run: |
          forge fmt --check

      - name: Run Forge Tests
        run: |
          forge coverage --force --report lcov -vvv

      - name: Report Code Coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: lcov.info
          minimum-coverage: 20
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .

      - name: Install Aderyn
        run: |
          forge fmt --check

      - name: Run Aderyn
        run: |
          aderyn

      - name: Upload Aderyn Report
        run: |
          cat report.md >> $GITHUB_STEP_SUMMARY